= Deploy Cloudstate Chat sample on Lightbend Cloudstate
Lightbend, 2020
Version 2.0, 2020-07-06
:description: Cloudstate Chat Application
:keywords: Lightbend Cloudstate, stateful, serverless, chat-sample, tutorial, LBCS
:sectnums:
:toc:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

[deploy-cscluster-overview]
== Overview

You have built the 3 microservices composing the Chat application:

* `chat-ui` a stateless service serving the UI
* `friends` a stateful service to manage the friend list of an user
* `presence` a stateful service to maintain the online state of an user

You have built the docker images of these services and published these images to your Docker registry. You have also run each of these images and tested that the service is in working order.

If this is not the case, please review <<../README.adoc#cs-chat-sample-overview,Cloudstate Sample Chat Application>> to complete the prerequisites.

We are now ready to deploy the Chat application, which we have chosen to deploy using Lightbend Cloudstate (managed hosting). Compared to the alternative of deploying on your own Kubernetes cluster, Lightbend Cloudstate relieves the developer from the burden related to the infrastructure:

* no need to provision hardware to setup (and maintain!) a Kubernetes cluster
* simplify network configuration
* simplify deployment


== Prerequisites

* Get [your Lightbend Cloudstate Account](https://docs.lbcs.io/gettingstarted/account.html)
* Install [akkasls](https://docs.lbcs.io/getting-started/set-up-development-env.html)

[[signup-cloudstate-account]]
=== Sign-up Cloudstate account

With your Lightbend Cloudstate account, you will be granted a Kubernetes cluster on the cloud. This cluster is managed by Lightbend Cloudstate. It is customized to host services created using the https://github.com/cloudstateio/cloudstate[Cloudstate library].

Instructions: https://docs.lbcs.io/getting-started/lightbend-account.html[Using a Cloudstate account]


=== Install Cloudstate CLI

`akkasls` is the command line tool that you will use to deploy an application on your Cloudstate cluster. Instructions: https://docs.lbcs.io/getting-started/set-up-development-env.html#_cloudstate_cli[Install Cloudstate CLI]

The `akkasls` minimum version required is 0.0.16 which you can verify by:

[source,shell]
----
$ akkasls version
0.0.16
----


=== Creating a Cloudstate project

A Cloudstate project is a space within your Cloudstate cluster. In this space, you will deploy your Cloudstate-aware application. In this step we use the Cloudstate CLI `akkasls` to:

* Login to your Cloudstate cluster (which you got when signing-up for a <<signup-cloudstate-account,Cloudstate account>>)
* Create a Cloudstate project
* Deploy your services in the project

More details on `akkasls` is available at https://docs.lbcs.io/cli/index.html[akkasls reference documentation].


[source,shell]
----
#===STEP1: connect akkasls to your Cloudstate account
$ akkasls auth login

#===STEP2: create a new Cloudstate project
# Syntax: akkasls project new "project-friendly-name" "Project description"
# NOTE: project-friendly-name: no space, only lower case and dash
$ akkasls project new chat-application "Chat room app built with Cloudstate services"

Created project chat-application.
To make this the currently active project, run: 'akkasls config set project chat-application'
  NAME               DESCRIPTION                                    STATUS    ID
  chat-application   Chat room app built with Cloudstate services   pending   3d864594-fefe-4708-82da-da842e4cdcde

#===STEP3: set the new Cloudstate project as "current"
$ akkasls config set project chat-application

Project set to chat-application
----

IMPORTANT:: A newly created project is in `pending` status, ie. you cannot yet deploy on your Cloudstate cluster.
Once the project is activated by a Cloudstate administrator (within a short moment). Its status will change to `active`, at which point, you can begin to deploy your services. In case it takes long time for your project to get activated, you can https://docs.lbcs.io/getting-started/create-project.html#_project_status[notify Cloudstate admin]

Confirm your Cloudstate project is ready for deployment:

* The project status is `active`
* The project is set as current. This helps to skip the `--project` parameter in `akkasls` commands when deploying on your Cloudstate cluster

[source,shell]
----
$ akkasls project list

# Notice the `*` (marker for current project) in front of the project name
  NAME               DESCRIPTION                                    STATUS   ID
* chat-application   Chat room app built with Cloudstate services   active   3d864594-fefe-4708-82da-da842e4cdcde
----

== Deployment

Now we are ready to deploy our Chat application on our Cloudstate cluster. The deployment tool is also `akkasls`.

At this point you should have all your docker images published in your Docker registry, as mentioned in the <<deploy-cscluster-overview, Overview section>>. In case you Docker registry is private, the `akkasls` needs to be configured with the corresponding credentials.

[source,shell]
----
$ akkasls docker add-credentials

# verify
$ akkasls docker list-credentials
----

In case you don't have your own docker images, you can still proceed with the deployment, using the images prebuilt by the Cloudstate project team.

=== Deploying chat-ui service

We deploy the `chat-ui` first as this is the entrypoint of the Chat application

[source,shell]
----
# Syntax: $ akkasls services deploy <serviceName> <dockerImageCoordinatess>
$ akkasls services deploy chat-ui lightbend-docker-registry.bintray.io/cloudstate-samples/chat-ui:latest

# give the cluster about a minute to provision the resources
# then verify that the service has `STATUS=Ready`
$ akkasls services get

# console output
NAME      AGE   REPLICAS   STATUS   DESCRIPTION
chat-ui   86s   1          Ready
----


The `chat-ui` service needs to be exposed to allow external access. Notice the service entrypoint given in the console output.

[source,shell]
----
$ akkasls service expose chat-ui

# console output
Service 'chat-ui' was successfully exposed at: little-cherry-4517.us-east1.apps.lbcs.io
----

=== Deplopying dependent services

Next we deploy the backend services:

[source,shell]
----
$ akkasls services deploy friends  lightbend-docker-registry.bintray.io/cloudstate-samples/chat-friends-js:latest
$ akkasls services deploy presence lightbend-docker-registry.bintray.io/cloudstate-samples/chat-presence-js:latest

# wait about a minute and check that all services are `Ready`
$ akkasls services get

# console output
NAME       AGE     REPLICAS   STATUS   DESCRIPTION
chat-ui    10m     1          Ready
friends    2m14s   1          Ready
presence   2m5s    1          Ready
----


WARNING: Normally, this is all we need to do to deploy the Chat application. For now, `akkasls` needs some workarounds to help the `chat-ui` to route service calls to dependant services. The step shown below is a temporary workaround. In the next version of `akkasls` this step will be unnecessary.
{nbsp} +
{nbsp} +
Route all calls using the same endpoint as `chat-ui`, which was given by `akkasls service expose chat-ui` in the previous step. Internally, Lightbend Cloudstate will forward the calls to `friends` and `presence` services to the appropriate endpoints.
{nbsp} +
{nbsp} +
We also need to know the fully qualified name of the service which are given by the gRPC service descriptors https://github.com/cloudstateio/samples-ui-chat/blob/master/chat-ui/chatapp_protos/friends.proto#L28[friends.proto] and https://github.com/cloudstateio/samples-ui-chat/blob/master/chat-ui/chatapp_protos/presence.proto#L18[presence.proto].


[source,shell]
----
$ akkasls service expose friends \
  --hostname little-cherry-4517.us-east1.apps.lbcs.io \
  --uri-prefix=/cloudstate.samples.chat.friends.Friends/

$ akkasls service expose presence \
  --hostname little-cherry-4517.us-east1.apps.lbcs.io \
  --uri-prefix=/cloudstate.samples.chat.presence.Presence/
----


== Testing the Chat Application

By design, the route to access the Chat UI is `/pages/chat.html`. Using the chat-ui service entrypoint obtained when running `akkasls service expose chat-ui`, our Chat application is accessible at:

----
https://little-cherry-4517.us-east1.apps.lbcs.io/pages/chat.html
----

That's it. Now enjoy the app, the navigation guide is explained at <<../README.adoc#chatui-navigation-guide,Chat navigation guide>>

*(end)*
